version: "3"

services:
    netmix:
        image: "teng315/netmix:1.0"
        hostname: "netmix"
        ports:
            - "8080:80"
            - "2222:22"
            - "8888:8888"
        volumes:
            - ./volumes/netmix/config/tinyproxy.conf:/etc/tinyproxy/tinyproxy.conf:rw
            - ./volumes/netmix/config/sshd_config:/etc/ssh/sshd_config:rw
            - ./volumes/netmix/config/openvpn.conf:/etc/openvpn/client.conf:rw
            - ./volumes/netmix/config/nginx-web.conf:/etc/nginx/conf.d/default.conf:rw
            - ./volumes/netmix/index.php:/home/www/index.php:rw
            - ./volumes/netmix/ntunnel_mysql.php:/home/www/ntunnel_mysql.php:rw
        environment:
            TIME_ZONE: "TIME_ZONE"
        cap_add:
            - NET_ADMIN
        restart: always
        extra_hosts:
            - "netmix.cn:${MAIN_HOST_IP}"
        networks:
            - default
            - dev-network
networks:
    default:
    dev-network:
        driver: bridge
        ipam:
            config:
                - subnet: ${NETWORK_SEGMENT}
